Ejercicio 1 con NumPy

In [1]:
import numpy as np
matriz_uno = np.arange(9).reshape(3,3)
print("La primer matriz es:")
print(matriz_uno)
print("La segunda matriz es:")
matriz_dos = np.arange(16).reshape(4,4)
print(matriz_dos)
print("De la segunda matriz extraemos la matriz 3:")
matriz_tres = matriz_dos[1:, 1:]
print(matriz_tres) #Hacemos slicing
print("Y sumamos las matrices 1 y 3:")
print(matriz_uno + matriz_tres)

La primer matriz es:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
La segunda matriz es:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
De la segunda matriz extraemos la matriz 3:
[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
Y sumamos las matrices 1 y 3:
[[ 5  7  9]
 [12 14 16]
 [19 21 23]]


Ejercicio con Pandas

Ejercicio con Matplotlib