Ejercicio 1 con NumPy

In [1]:
import numpy as np
matriz_uno = np.arange(9).reshape(3,3)
print("La primer matriz es:")
print(matriz_uno)
print("La segunda matriz es:")
matriz_dos = np.arange(16).reshape(4,4)
print(matriz_dos)
print("De la segunda matriz extraemos la matriz 3:")
matriz_tres = matriz_dos[1:, 1:]
print(matriz_tres) #Hacemos slicing
print("Y sumamos las matrices 1 y 3:")
print(matriz_uno + matriz_tres)

La primer matriz es:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
La segunda matriz es:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
De la segunda matriz extraemos la matriz 3:
[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
Y sumamos las matrices 1 y 3:
[[ 5  7  9]
 [12 14 16]
 [19 21 23]]


Ejercicio con Pandas (y NumPy)

In [4]:
import pandas as pd
import numpy as np
print("*Tenemos la siguiente base de datos sobre la informacion de los huespedes enviados por diferentes compañias a un hotel y las plataformas a traves de las cuales se hicieron las reservaciones:")
df = pd.read_csv("https://chandoo.org/wp/wp-content/uploads/2022/09/hotel-booking-data.txt", delimiter="\t")
print(df.head())
print("*El numero de huespedes enviados por cada empresa es:")
print(df["Company"].value_counts())
print("*Dentro de las reservas que vienen a través de Expedia, ¿qué persona se hospedó por parte de la empresa Tazz y a travez de los servicios de Booking?")


*Tenemos la siguiente base de datos sobre la informacion de los huespedes enviados por diferentes compañias a un hotel y las plataformas a traves de las cuales se hicieron las reservaciones:
         Date Company        Person Name  Room number
0  1-Jan-2022  Avamba  Anatole Ridehalgh       4008.0
1  1-Jan-2022    Fatz    Aldrich McKevin       2002.0
2  1-Jan-2022   Leexo    Stanley Hadrill       4012.0
3      Hotels     NaN                NaN          NaN
4  1-Jan-2022  Rhyzio       Lyndell Tice       1006.0
*El numero de huespedes enviados por cada empresa es:
Company
Leexo           3
Quinu           3
Fivechat        3
Twitterlist     2
Jayo            2
               ..
Twitterwire     1
Skiba           1
Tagpad          1
Innojam         1
Twitterworks    1
Name: count, Length: 114, dtype: int64
*Dentro de las reservas que vienen a través de Expedia, ¿qué persona se hospedó por parte de la empresa Tazz y a travez de los servicios de Booking?


Ejercicio con Matplotlib